name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  contents: read
  packages: write
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/playwright-demo
      IMAGE_TAG: ${{ github.sha }}
      FULL_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/playwright-demo:${{ github.sha }}
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build --tag $FULL_IMAGE_NAME .
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
    - name: Push Docker image to GHCR
      run: docker push $FULL_IMAGE_NAME
    - name: Run Playwright tests in Docker
      run: docker run --rm -v ${{ github.workspace }}/playwright-report:/app/playwright-report $FULL_IMAGE_NAME
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
